[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
serde = { version = "1.0.106", features = ["derive"] }
utils={path = "../utils"}
failure = "0.1"
rust-crypto = "^0.2"
sled = "0.34"